# choices/provinces.py

PROVINCE_CHOICES = [
    ("Álava", "Álava"),
    ("Albacete", "Albacete"),
    ("Alicante", "Alicante"),
    ("Almería", "Almería"),
    ("Asturias", "Asturias"),
    ("Ávila", "Ávila"),
    ("Badajoz", "Badajoz"),
    ("Barcelona", "Barcelona"),
    ("Burgos", "Burgos"),
    ("Cáceres", "Cáceres"),
    ("Cádiz", "Cádiz"),
    ("Cantabria", "Cantabria"),
    ("Castellón", "Castellón"),
    ("Ciudad Real", "Ciudad Real"),
    ("Córdoba", "Córdoba"),
    ("Cuenca", "Cuenca"),
    ("Girona", "Girona"),
    ("Granada", "Granada"),
    ("Guadalajara", "Guadalajara"),
    ("Guipúzcoa", "Guipúzcoa"),
    ("Huelva", "Huelva"),
    ("Huesca", "Huesca"),
    ("Illes Balears", "Illes Balears"),
    ("Jaén", "Jaén"),
    ("La Coruña", "La Coruña"),
    ("La Rioja", "La Rioja"),
    ("Las Palmas", "Las Palmas"),
    ("León", "León"),
    ("Lleida", "Lleida"),
    ("Lugo", "Lugo"),
    ("Madrid", "Madrid"),
    ("Málaga", "Málaga"),
    ("Murcia", "Murcia"),
    ("Navarra", "Navarra"),
    ("Ourense", "Ourense"),
    ("Palencia", "Palencia"),
    ("Pontevedra", "Pontevedra"),
    ("Salamanca", "Salamanca"),
    ("Santa Cruz de Tenerife", "Santa Cruz de Tenerife"),
    ("Segovia", "Segovia"),
    ("Sevilla", "Sevilla"),
    ("Soria", "Soria"),
    ("Tarragona", "Tarragona"),
    ("Teruel", "Teruel"),
    ("Toledo", "Toledo"),
    ("Valencia", "Valencia"),
    ("Valladolid", "Valladolid"),
    ("Vizcaya", "Vizcaya"),
    ("Zamora", "Zamora"),
    ("Zaragoza", "Zaragoza"),
    ("Ceuta", "Ceuta"),
    ("Melilla", "Melilla"),
]
